# Generated by Django 5.1.2 on 2025-02-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0013_companyregister_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='contacted',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='shortlisted',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('contacted', 'Contacted'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the application', max_length=15),
        ),
    ]
